# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /media/shimko/CEF0BAC0F0BAADD9/workspace/references/freertos_mastering/fpga/bd/freertos_mastering/freertos_mastering.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==freertos_mastering || ORIG_REF_NAME==freertos_mastering} -quiet] -quiet

# IP: /media/shimko/CEF0BAC0F0BAADD9/workspace/references/freertos_mastering/fpga/bd/freertos_mastering/ip/freertos_mastering_processing_system7_0_0/freertos_mastering_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==freertos_mastering_processing_system7_0_0 || ORIG_REF_NAME==freertos_mastering_processing_system7_0_0} -quiet] -quiet

# XDC: /media/shimko/CEF0BAC0F0BAADD9/workspace/references/freertos_mastering/fpga/bd/freertos_mastering/freertos_mastering_ooc.xdc
