# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/shimko/CEF0BAC0F0BAADD9/workspace/references/freertos_mastering/fpga/bd/freertos_mastering/ip/freertos_mastering_processing_system7_0_0/freertos_mastering_processing_system7_0_0.xci
# IP: The module: 'freertos_mastering_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/shimko/CEF0BAC0F0BAADD9/workspace/references/freertos_mastering/fpga/bd/freertos_mastering/ip/freertos_mastering_processing_system7_0_0/freertos_mastering_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'freertos_mastering_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/shimko/CEF0BAC0F0BAADD9/workspace/references/freertos_mastering/fpga/bd/freertos_mastering/ip/freertos_mastering_processing_system7_0_0/freertos_mastering_processing_system7_0_0.xci
# IP: The module: 'freertos_mastering_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/shimko/CEF0BAC0F0BAADD9/workspace/references/freertos_mastering/fpga/bd/freertos_mastering/ip/freertos_mastering_processing_system7_0_0/freertos_mastering_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'freertos_mastering_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
